{% set version = "3.19.4" %}

package:
  name: cmake
  version: {{ version }}

source:
  url: https://github.com/Kitware/CMake/releases/download/v{{ version }}/cmake-{{ version }}.tar.gz
  sha256: 7d0232b9f1c57e8de81f38071ef8203e6820fe7eec8ae46a1df125d88dbcc2e1
  # Not until Python 3.8 on Windows: https://github.com/WorksApplications/SudachiPy/issues/107#issuecomment-564510365
  # path: 'C:/opt/Shared.local/src/cmake'
  # path_via_symlink: True
  # folder: cmake
  # git_url: 'C:/opt/Shared.local/src/cmake'
  # git_url: 'https://gitlab.kitware.com/cmake/cmake'
  # patches:
  #   - patches/git/0001-Add-more-debug-logging-to-cmFindCommon.patch

build:
{% if bootstrapping == 'yes' %}
  number: 0
  string: h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}_bootstrapping
  script_env:
    - BOOTSTRAPPING=yes
{% else %}
  # Keep above the number of the _bootstrapping package
  number: 1
{% endif %}
  ignore_run_exports:
    - vc

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make            # [unix]
    - patch           # [not win]
    - m2-patch        # [win]
{% if bootstrapping != 'yes' %}
    - cmake           # [build_platform != target_platform]
{% endif %}

  host:
    - openssl         # [unix]
    - ncurses         # [unix]
{% if bootstrapping != 'yes' %}
    - bzip2           # [unix]
    - libcurl         # [unix]
    - expat           # [unix]
    - xz              # [unix]
    - zlib            # [unix]
    - libuv           # [unix]
    - rhash           # [unix]
    - zstd            # [unix]
{% endif %}
  run:
    - openssl         # [unix]
    - ncurses         # [unix]
{% if bootstrapping != 'yes' %}
    - bzip2           # [unix]
    - libcurl         # [unix]
    - expat           # [unix]
    - xz              # [unix]
    - zlib            # [unix]
    - libuv           # [unix]
    - rhash           # [unix]
    - zstd            # [unix]
{% endif %}
    - vs2015_runtime  # [win]

test:
  files:
    - SSLTest.cmake
  commands:
    - cmake --version
    - cmake -V -P SSLTest.cmake
    - ctest --version
    - cpack --version
    - ccmake --version  # [unix]

about:
  home: http://www.cmake.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - Copyright.txt
    - Utilities/cmbzip2/LICENSE         # [win]
    - Utilities/cmcurl/COPYING          # [win]
    - Utilities/cmexpat/COPYING         # [win]
    - Utilities/cmliblzma/COPYING       # [win]
    - Utilities/cmzlib/Copyright.txt    # [win]
    - Utilities/cmlibuv/LICENSE         # [win]
    - Utilities/cmlibrhash/COPYING      # [win]
    - Utilities/cmlibarchive/COPYING
    - Utilities/cmjsoncpp/LICENSE
  summary: CMake is an extensible, open-source system that manages the build process

extra:
  recipe-maintainers:
    - blowekamp
    - groutr
    - jakirkham
    - jschueller
    - ocefpaf
    - msarahan
    - scopatz
    - tadeu
    - marcelotrevisani
